services:
  # ------ PostgreSQL ------- #
  postgres:
    image: postgres:16.8-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myllypuro-campus
    command: -p 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # ------ TimescaleDB ------- #
  timescaledb:
    image: timescale/timescaledb:2.17.2-pg16
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myllypuro-campus
    command: -p 5433
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  # ------ Data Service ------- #
  data-service:
    container_name: data-service
    build:
      context: ./data-service
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    environment:
      - DATABASE_URL_PLATFORM=postgresql://postgres:postgres@postgres:5432/myllypuro-campus
      - DATABASE_URL_TIMESCALE=postgresql://postgres:postgres@timescaledb:5433/myllypuro-campus
      - PORT=3010
      - LOG_LEVEL="info" 
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # Database connection configuration for entrypoint script
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - TIMESCALE_HOST=timescaledb
      - TIMESCALE_PORT=5433
      # Auth configuration
      - AUTH_ENABLED=false
      - DISTRIBUTED_DEPLOYMENT=false
    volumes:
      - ./data-service:/app
      - /app/node_modules
      - ./data-service/generated:/app/generated
    depends_on:
      - timescaledb
      - postgres

  # # ------ Timescale Writer ------- #
  # timescale-writer:
  #   container_name: timescale-writer
  #   build:
  #     context: ./timescale-writer
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092
  #     - KAFKA_TOPICS=smartlab-sensor-data
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=myllypuro-campus
  #     - POSTGRES_HOST=timescaledb
  #     - POSTGRES_PORT=5433
  #     - NODE_ENV=development
  #   volumes:
  #     - ./timescale-writer:/app
  #     - /app/node_modules
  #   depends_on:
  #     - timescaledb
  #     - kafka
  #   profiles: ["storage", "full"]

volumes:
  timescaledb_data:
  postgres_data: