services:
  # ------ PostgreSQL ------- #
  postgres:
    image: postgres:16.8-bookworm
    container_name: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: platform
    command: -p 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d platform"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # ------ TimescaleDB ------- #
  timescaledb:
    image: timescale/timescaledb:2.17.2-pg16
    container_name: timescaledb
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timescale
    command: -p 5432
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timescale"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------ Data Service ------- #
  data-service:
    container_name: data-service
    build:
      context: ./data-service
      dockerfile: Dockerfile.dev
    env_file:
      - path: ./data-service/.env.example
        required: true
    ports:
      - "3010:3010"
    volumes:
      - ./data-service:/app
      - /app/node_modules
      - ./data-service/generated:/app/generated
    depends_on:
      postgres:
        condition: service_healthy
      timescaledb:
        condition: service_healthy

  # # ------ Timescale Writer ------- #
  # timescale-writer:
  #   container_name: timescale-writer
  #   build:
  #     context: ./timescale-writer
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - path: ./timescale-writer/.env.example
  #       required: true
  #   volumes:
  #     - ./timescale-writer:/app
  #     - /app/node_modules
  #   depends_on:
  #     - timescaledb
  #     - kafka
  #   profiles: ["timescale-writer", "storage", "full"]

volumes:
  timescaledb_data:
  postgres_data: