version: '3'

services:
  # ------ TimescaleDB ------- #
  timescaledb:
    image: timescale/timescaledb:2.17.2-pg16
    container_name: timescaledb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myllypuro-campus
    volumes:
      - ./databases/timescaledb:/docker-entrypoint-initdb.d
      - timescaledb_data:/var/lib/postgresql/data
    profiles: ["infra", "database", "timescaledb"]

  # ------ Kafka ------- #
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    profiles: ["infra", "kafka"]

  # ------ Kafka UI ------- #
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - '8080:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: metropolia
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    profiles: ["infra", "kafka"]

  # ------ MQTT Subscriber ------- #
  mqtt-subscriber:
    container_name: mqtt-subscriber
    build:
      context: .
      dockerfile: ./services/mqtt_subscriber/Dockerfile
    environment:
      - MQTT_BROKER=xrdevmqtt.edu.metropolia.fi
      - MQTT_PORT=1883
      - MQTT_CLIENT_ID=mqtt-subscriber
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_QOS=0
      - MQTT_KEEP_ALIVE=30
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC_SENSOR_DATA=smartlab-sensor-data
      - KAFKA_TOPIC_SERVICE_METRICS=smartlab-subscriber-metrics
      - API_PORT=3000
      - RUST_LOG=info
    ports:
      - '3000:3000'
    profiles: ["connectors", "mqtt-subscriber"]

  # ------ Timescale Writer ------- #
  timescale-writer:
    container_name: timescale-writer
    build:
      context: .
      dockerfile: ./services/timescale-writer/Dockerfile
    environment:
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPICS=smartlab-sensor-data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myllypuro-campus
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
    volumes:
      - ./services/timescale-writer:/app
    profiles: ["connectors", "timescale-writer"]

volumes:
  timescaledb_data:
