name: campus-dev

include:
  # Core services - always included (no profile needed)
  - ./modules/data-streaning/docker-compose.datastreaming.yml
  - ./modules/storage/docker-compose.storage.yml
  - ./modules/ingress/docker-compose.ingress.yml
  
  # Optional services - controlled by profiles defined in their respective files
  - ./modules/analytics/docker-compose.analytics.yml
  - ./modules/app/docker-compose.app.yml
  - ./modules/egress/docker-compose.egress.yml

# Global networks that can be shared across modules
networks:
  iot-platform-network:
    driver: bridge
    name: iot-platform-network

# Global volumes that can be shared across modules
volumes:
  shared-data:
    name: iot-platform-shared-data
