version: "3.8"
services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile

    environment: !reset
    env_file: !reset
    healthcheck: !reset

    volumes:
      - ..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
